### ISSUE TITLE
401 error renewing locks after the receiver has been open for a few hours

### ISSUE THREAD

**Issue by bmnielsen** [Azure/azure-service-bus-go#155] opened 2020-01-15 13:11 UTC
I'm trying to set up lock renewal in my service bus consumer, as processing the items often takes more than the maximum timeout of 5 minutes, but I'm having problems renewing the locks after the service has been running for a few hours.

At startup I initialize the namespace and queue, create a receiver, and call `Listen` to start receiving messages. The handler function does the following:

1. Create a cancellable context
2. Start a goroutine that will renew the message lock every 30 seconds until the above context is cancelled
3. Process the item
4. Cancel the above context to signal the lock renewal goroutine to stop
5. Complete the message handling by calling `Complete` or `DeadLetter` on the message as appropriate

Everything is fine for the first hour or two, but then all calls to the `queue.RenewLocks(...)` command start returning this error:

`unhandled error link {uuid}: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation.`

This only affects lock renewal; the receiver continues running and getting messages as normal, but as their locks fail to renew, they are delivered multiple times and eventually end up on the DLQ.

**Comment by XavierGeerinck** [comment] 2021-01-26 07:47
If I may add @jhendrixMSFT  to this, this is a quite critical issue I would say... I am using Service Bus as well but it's close to impossible to use it in production with this bug there. My application stops working after ~11h due to this bug.

> Note: I am utilizing it through Dapr, but it appears to be a Service Bus Go SDK issue seeing the bug in this thread.

The message I am seeing:

```
time="2021-01-24T17:06:41.287841541Z" level=info msg="placement tables updated, version: 0" app_id=my-app instance=d-my-app-b5cb647-tn24x scope=dapr.runtime.actor.internal.placement type=log ver=1.0.0-rc.2
time="2021-01-25T03:40:24.331907339Z" level=warning msg="Couldn't renew all active message lock(s) for topic topic-my-app, %!(EXTRA common.Retryable=unhandled error link MASKED-c8d1-4fb3-8f63-3bcef93cd6c4: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://sb-my-app-prod.servicebus.windows.net/topic-my-app/subscriptions/my-app/$management'. TrackingId:9e0bfb92-7c1e-4b04-94c9-d37a43a1de35_G20, SystemTracker:NoSystemTracker, Timestamp:2021-01-25T03:40:23)" app_id=my-app instance=d-my-app-b5cb647-tn24x scope=dapr.contrib type=log ver=1.0.0-rc.2
```

**Comment by bmnielsen** [comment] 2021-01-26 08:06
We worked around this by having our lock renewal goroutine get a new connection to the queue / topic every time, which is tremendously inefficient but does work.

**Comment by XavierGeerinck** [comment] 2021-01-26 08:09
Thanks a lot for your input @bmnielsen !!! I might look into this, but wondering how I should tackle this since I am using this library through Dapr... 

Seeing that I am using it through Dapr I guess this should be fixed here rather than through Dapr? (else introducing a bug more downstream rather than in the source?)

**Comment by georgestevens99** [comment] 2021-01-26 13:53
IMO this bug should be fixed here in the go routine for the Service Bus only.  Getting a new connection periodically (even every time) is better than software that mysteriously breaks after running OK for a number of hours.  

Also note that this problem with the Azure Service Bus may not be new.  Back in 2015 and 2016 myself and a few others were working intensely developing WCF services that used the WCF NetMessagingBinding to access Azure Service Bus Queues.  There were numerous instances where in production systems the WCF NetMessagingBinding would mysteriously stop receiving messages.  Our work around was to stop and restart the WCF Service Host program (which hosted the WCF service using the NetMessagingBinding).  And this worked fine.  Essentially it re-established the connection to the Service Bus.  I have no explicit evidence that WCF NetMessagingBinding problems are related to the problem in the Dapr go routine.  However, without fixing the problem in the go routine, then ultimately one must resort to restarting the processes using the flawed binding as a work around.  I'd rather sacrifice  efficiency of my code than have to restart services or do things in my own code to get reception of incoming messages working consistently.

**Comment by jhendrixMSFT** [comment] 2021-01-28 16:00
@catalinaperalta and I are investigating this, will update as we have more info.

**Comment by jhendrixMSFT** [comment] 2021-01-28 18:02
We've been digging into this.  One thing that stands out to us is that we ignore any errors encountered during auto-refresh of the SAS token.  https://github.com/Azure/azure-service-bus-go/blob/master/sender.go#L392

We do log it in the tracing though.  I don't suppose anybody has a trace log that would indicate this is failing?

**Comment by XavierGeerinck** [comment] 2021-01-28 18:07
Thanks for investigating! Sadly enough I do not have any tracing logs besides the ones provided above :)

**Comment by jhendrixMSFT** [comment] 2021-01-28 18:13
Possibly related https://github.com/Azure/azure-service-bus-go/issues/198

**Comment by catalinaperalta** [comment] 2021-01-28 18:38
Would anybody on this thread have repro code they could share with us?

**Comment by XavierGeerinck** [comment] 2021-01-28 18:48
I am utilizing this through Dapr (Microsoft) which is implementing this here: https://github.com/dapr/components-contrib/blob/master/pubsub/azure/servicebus/servicebus.go

The subscribe topic is highlighted here: https://github.com/dapr/components-contrib/blob/master/pubsub/azure/servicebus/servicebus.go#L264

Does this help?

**Comment by catalinaperalta** [comment] 2021-01-28 18:53
Taking a look, thanks for the info!

**Comment by eccles** [comment] 2021-02-08 14:36
I have this problem as well - any progress?

**Comment by jhendrixMSFT** [comment] 2021-02-08 15:38
We've been struggling with getting a repro on our side.  If anybody on this thread has a reasonably simple repro and/or can share any details about their SB environment (pricing tier) it would be a big help.

**Comment by jjcollinge** [comment] 2021-02-13 18:05
@jhendrixMSFT I'm not sure how familiar you are with [Dapr](https://dapr.io/) but I am able to repro it using that - although it's a little hard to debug.

1. Spin up a kubernetes cluster
2. [Install dapr cli ](https://v1-rc2.docs.dapr.io/getting-started/install-dapr-cli/)
3. Deploy dapr to the kubernetes cluster using `dapr init -k`
4. Deploy an Azure Service Bus namespace.
5. Go the following [gist](https://gist.github.com/jjcollinge/1cea55ad78fe323040accd90aa02b49d).
6. Add your connection string to the file `pubsub.yaml`.
7. Deploy the pubsub dapr component using `kubectl apply -f pubsub.yaml`
8. Go over to the [Dapr quickstarts](https://github.com/dapr/quickstarts/tree/master/pub-sub) and deploy the `node-subscriber` and `python-subscriber`.
9. Finally deploy the `dapr-pub.yaml` from the gist (step 5).
10. Watch the logs of the `node-subscriber` to ensure messages are coming through i.e. ` k logs -f node-subscriber-5b94cf775b-mdcgp node-subscriber`.
11. Leave these apps running for some time and you should eventually start to the see the same issue in the dapr logs i.e. `k logs -f node-subscriber-5b94cf775b-mdcgp daprd`

Happy to talk through this if you'd rather do that.

Hope that helps.

**Comment by georgestevens99** [comment] 2021-02-13 18:26
Thanks for chasing that down.

If time permits, it would be revealing to run your tests above WITHOUT
Dapr, i.e. just using a standard Azure Topic Client to publish to a topic,
leaving all else the same as much as possible.

I believe that such a test will also surface the same (publish stops
working after a time) symptom, although with different error messages of
course.  This will indicate that the underlying bug is in the Service Bus
code somewhere, and not due to Dapr.

Thanks again,
George Stevens

**Comment by jjcollinge** [comment] 2021-02-13 18:32
Thanks @georgestevens99 - I'll take a look next week if I can decouple it from Dapr. Although I have only seen this issue in relation to subscribers who are renewing locks whilst they process messages. Eventually the renewal starts failing with 401. I haven't seen the same on a publishing connection.

**Comment by georgestevens99** [comment] 2021-02-13 19:01
Oops. I was mistaken.  I should have said receiving messages.  My
apologies.  Nevertheless, it may be telling to see what happens when
plain-old Service Bus topic receiving code is used in place of the Dapr
Pub/Sub code.  That could prove the problem is in the Service Bus message
receiving code and not in Dapr.  There was some indication of this in
related issues.

Thanks,
George

**Comment by georgestevens99** [comment] 2021-02-13 19:13
Just to be clear, it would be useful to completely remove dapr and replace
it with the Service Bus libraries for both publish and receive, so as to
see if the receive exception happens without dapr being in the process.  I
am multi-multi tasking today so please pardon my rather disjointed input.
I just want to see if the root cause of this bug can be identified.
Thanks,
George

**Comment by catalinaperalta** [comment] 2021-02-17 15:24
I agree with @georgestevens99, I've been trying to reproduce this with the service bus go code directly to see where the error could be on the SDK side.

**Comment by jhendrixMSFT** [comment] 2021-02-17 17:19
Can you please try updating to `v0.10.10` to see if it resolves the issue?

**Comment by jjcollinge** [comment] 2021-02-17 17:42
@jhendrixMSFT I'll try `v0.10.10` with dapr and see if it helps. @catalinaperalta I'm running some tests now without dapr too - I'll let you know the results.

**Comment by jjcollinge** [comment] 2021-02-17 19:20
@catalinaperalta I've got a simple receiver program that does repro the issue outside of dapr here: https://gist.github.com/jjcollinge/1cea55ad78fe323040accd90aa02b49d#file-main-go
It may be that I'm misusing the SDK so if that's the case please let me know. There are a number of issues with this sample i.e. using a global array in a non thread safe way but it should be ok to demonstrate the issue. I ran this for just over 2 hours whilst publishing messages to the topic and then started receiving `Error renewing locks: unhandled error link dce13ef3-d645-4837-a2ee-7693c51229d9: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation`. This was using `v0.10.7` so tomorrow I'll rerun with `v0.10.10`.

**Comment by georgestevens99** [comment] 2021-02-17 19:31
Excellent news!  Thanks for going the extra mile to track this bug down.
George

**Comment by georgestevens99** [comment] 2021-02-17 19:50
Perhaps think about this when considering a fix outside the service bus
code itself:
1.  Does any message loss occur during the "Unauthorized Access" error?
2.  If not, can the reciever code just reconnect (i.e. create a new service
bus queue or topic client) and resume processing messages AND not risk ever
loosing messages.  And keep receiving until the next "Unauthorized Access"
error, and then do the same, over and over?

The above suggestions may not be the best solution, but may shed insight on
issues to consider in the universe of useful solutions at the Dapr level.

Thanks,
George

**Comment by jhendrixMSFT** [comment] 2021-02-17 21:28
Thanks for providing the repo.  The problem here is that in `v0.10.9`, if `Recover()` is called on a sender/receiver the auto-refreshing of auth isn't restarted, i.e. we don't call `periodicallyRefreshAuth()` after recovering the connection.  So at that point, the credentials are good for 2 hours, and if the connection isn't recovered again for whatever reason, they will expire.  This has been fixed in `v0.10.10` so I'm closing this issue.  Thanks everybody for all the help and patience.

**Closed by jhendrixMSFT** 2021-02-17 21:28 UTC

**Comment by jjcollinge** [comment] 2021-02-17 21:30
Thanks @jhendrixMSFT - glad we have a root cause. I'll bump the version in Dapr and validate the fix tomorrow.

**Comment by Samridhigupta786** [comment] 2021-02-26 14:11
> Thanks for providing the repo. The problem here is that in `v0.10.9`, if `Recover()` is called on a sender/receiver the auto-refreshing of auth isn't restarted, i.e. we don't call `periodicallyRefreshAuth()` after recovering the connection. So at that point, the credentials are good for 2 hours, and if the connection isn't recovered again for whatever reason, they will expire. This has been fixed in `v0.10.10` so I'm closing this issue. Thanks everybody for all the help and patience.

Hey, I'm using azure service bus sdk for go (v0.10.10), and I getting context canceled issue in the Receive function after every two hours to be more specific it is 2hr 10 mins, you have pointed out the crendential is valid for 2 hrs, are we not refreshing the authentication cred?  There seems to be having some issue with recieve func, this is causing lot of trouble with renewing locks, processing messages, because duue to context canceled, the messages that are being still processed are failing at renew lock as well as at msg.complete().

**Comment by jhendrixMSFT** [comment] 2021-02-26 15:19
@Samridhigupta786 can you please open a new issue to track this?  If you have any sample/repro code please include that as well.

**Comment by Samridhigupta786** [comment] 2021-02-26 15:49
> @Samridhigupta786 can you please open a new issue to track this? If you have any sample/repro code please include that as well.

Well, there's already an open issue related to receive func() giving context canceled. Here is the [link](https://github.com/Azure/azure-service-bus-go/issues/156), I also opened an issue in [stackoverflow](https://stackoverflow.com/questions/66385235/servicebus-queue-receive-returns-context-canceled-frquently-around-every-2), the reason I mention this issue here because we were getting this 401 error when renewing lock previously after few hours , and following the answers suggested here, we upgraded from v0.10.6 to v0.10.10 to fix this, now he get this context canceled in recieve func() frequently(every 2 hrs).
